name: Generate site and push to GitHub pages branch

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  generate_and_commit:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Checkout website repo on publish branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: master

      - name: Install elm
        uses: justgook/setup-elm@1.3.0
        with:
          elm-version: '0.19.1'

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Clone pushpin
        uses: actions/checkout@v3
        with:
          repository: tedbauer/pushpin
          ref: master
          path: cloned-repo

      - name: Clone pocket symphony
        uses: actions/checkout@v3
        with:
          repository: tedbauer/pocket-symphony
          ref: main
          path: pocket-symphony-repo

      - name: Build pocket symphony
        working-directory: pocket-symphony-repo
        run: |
          npm install --save-dev ts-loader
          make build

      - name: Move pocket symphony files to another dir
        working-directory: pocket-symphony-repo
        run: |
          cp index.html ../pocket-symphony.html
          cp main.js ../main.js
          cp stylesheet.css ../stylesheet.css
          mkdir -p ../dist
          cp dist/main.js ../dist/main.js

      - name: Build, install, and run pushpin
        working-directory: cloned-repo
        run: |
          cargo build --release
          PUSHPIN_PATH=$(pwd)/target/release/pushpin
          echo "PUSHPIN_PATH=$PUSHPIN_PATH" >> $GITHUB_ENV
          cd ..
          $PUSHPIN_PATH

      - name: Remove pushpin local clone
        run: rm -rf cloned-repo

      - name: Remove local clone of pocket symphony
        run: rm -rf pocket-symphony-repo

      - name: Commit changes and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git checkout -b gh-pages
          git commit -m "Automated file generation"
          git push https://${{ secrets.ACCESS_TOKEN }}@github.com/tedbauer/tedbauer.github.io HEAD:gh-pages --force
