name: Generate site and push to GitHub pages branch

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  generate_and_commit:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Checkout website repo on publish branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: gh-pages

      - name: Clone pushpin
        uses: actions/checkout@v3
        with:
          repository: tedbauer/pushpin
          ref: master
          path: cloned-repo 

      - name: Build, install, and run pushpin
        working-directory: cloned-repo
        run: |
          cargo build --release
          PUSHPIN_PATH=$(pwd)/target/release/pushpin
          echo "PUSHPIN_PATH=$PUSHPIN_PATH" >> $GITHUB_ENV
          cd ..
          $PUSHPIN_PATH

      - name: Commit changes and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Automated file generation"
          git push https://${{ secrets.ACCESS_TOKEN }}@github.com/tedbauer/tedbauer.github.io HEAD:gh-pages --force
